import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import ResponsiveAppBar from "@/components/ResponsiveAppBar";
import { Box, Toolbar, Typography } from "@mui/material";
import dynamic from "next/dynamic";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const MapWithNoSSR = dynamic(() => import("../components/LeafletMap"), {
    ssr: false
  })

  return (
    <>
      <Head>
        <title>TrascribeMe</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveAppBar/>
      <Box component="main" sx={{ p: 3 }}>
        <Toolbar />
      </Box>
    </>
  );
}
