import Head from "next/head";
import React, { useState } from "react";
import ResponsiveAppBar from "../components/ResponsiveAppBar";
import {
  Box,
  Button,
  Grid,
  Paper,
  Toolbar,
  Typography,
  styled,
} from "@mui/material";
import axios from "axios";

export default function Transcribe() {

  const [currentFile, setCurrentFile] = useState(null || "");

  function handleFileChange(event: React.FormEvent<HTMLInputElement>) {
    setCurrentFile(event.currentTarget.value);
  }

  return (
    <>
      <Head>
        <title>TranscribeMe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <ResponsiveAppBar />
      <Grid container component="main" sx={{ p: 3 }} alignItems="center" justifyContent="center" style={{minHeight: "100vh"}} spacing={0} direction="column">
        <Toolbar />
        <Grid container gap={2} spacing={2} flexGrow={1}  alignItems="center" justifyContent="center" sx={{flexDirection: {xs: "column", md: "row"}}}>
          <Button variant="contained" component="label">
            Upload Audio
            <input type="file" value={currentFile} accept="audio/*" onChange={handleFileChange} hidden  />
          </Button>
          <Button variant="contained">
            Lol submit
          </Button>
        </Grid>
      </Grid>
    </>
  );
}
