import Head from "next/head";
import React, { FormEvent, Ref, useRef, useState } from "react";
import ResponsiveAppBar from "../components/ResponsiveAppBar";
import FormInput from "../components/FormInput";
import {
  Box,
  Button,
  Container,
  Grid,
  Paper,
  Stack,
  TextField,
  Toolbar,
  Typography,
  styled,
} from "@mui/material";
import { MapContainer, ZoomControl } from "react-leaflet";
import axios from "axios";
import dynamic from "next/dynamic";
import { LatLng, Marker } from "leaflet";

export default function Transcribe() {
  const MapWithNoSSR = dynamic(() => import("../components/LeafletMap"), {
    ssr: false,
  });

  const formInputStateRef = useRef<any>();

  const [currentLocation, setCurrentLocation] = React.useState<[number, number]>([0,0]);

  return (
    <>
      <Head>
        <title>TranscribeMe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveAppBar />
      <Grid
        container
        component="main"
        sx={{ p: 3 }}
        style={{ minHeight: "100vh" }}
        spacing={0}
        direction="column"
      >
        <Toolbar />
        <Grid
          container
          gap={2}
          spacing={2}
          flexGrow={1}
          alignItems="center"
          justifyContent="center"
          direction="row"
        >
          <Stack spacing={2}>
            <FormInput ref={formInputStateRef}/>
            <MapWithNoSSR center={[40.4276, -86.9169]} locationTextFieldId="location" coordsTextFieldId="coords"/>
            <TextField
              id="location"
              variant="outlined"
              label="Location"
              defaultValue={" "}
              InputProps={{ readOnly: true }}
            ></TextField>
            <input
              id="coords"
              type="text"
              hidden />
          </Stack>
          <Grid item>
            <Button onClick={()=>{
              let formData = new FormData();
              const formInputData = formInputStateRef.current.getFormInput();
              formData.append("audioFile", formInputData.file);
              formData.append("title", formInputData.title);
              formData.append("recorder", formInputData.recorder);
              const coords = (document.getElementById("coords") as HTMLInputElement).value.split(",").map((value, index, array)=>{
                return parseFloat(value).toPrecision(6);
              });
              formData.append("lat", coords[0]);
              formData.append("lng", coords[1]);

            }} variant="contained">Lol submit</Button>
          </Grid>
        </Grid>
      </Grid>
    </>
  );
}
